### ISSUE TITLE
Transfer repo to ACCESS-NRI

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/dummygrib#1]
I had an offline conversation with @paolap about transferring this repository to the ACCESS-NRI organisation.

This is a tiny code stub that is necessary for the UM model to compile correctly in the absence of a licensed library. ACCESS-NRI needs access to this to support ACCESS-ESM1.5, so we're happy to transfer to our organisation and take responsibility for it.

If you reply with agreement @paolap I'll transfer the repo.

Pinging @scottwales as he wrote the code.

**Comment by paolap** [comment]
Be my guest! I agree 100%

**Comment by ScottWales** [comment]
👍

On 4 Apr 2024, at 4:09 pm, Aidan Heerdegen ***@***.***> wrote:

﻿

I had an offline conversation with @paolap<https://github.com/paolap> about transferring this repository to the ACCESS-NRI organisation.

This is a tiny code stub that is necessary for the UM model to compile correctly in the absence of a licensed library. ACCESS-NRI needs access to this to support ACCESS-ESM1.5, so we're happy to transfer to our organisation and take responsibility for it.

If you reply with agreement @paolap<https://github.com/paolap> I'll transfer the repo.

Pinging @ScottWales<https://github.com/ScottWales> as he wrote the code.

**Comment by aidanheerdegen** [comment]
Done
