### ISSUE TITLE
Add build CI

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/dummygrib#2]
Despite this being little more than a stub library to satisfy linking dependencies, we should still add Build CI for completeness, and because it is simple to do so.

Uses the [`dummygrib` package](https://github.com/ACCESS-NRI/spack-packages/tree/main/packages/dummygrib).

Should add branch protections also.

**Comment by CodeGat** [comment]
Build CI added, branch protections added!
